# fly.toml app configuration file generated for practice5-deploy-netlify on 2023-10-23T19:45:15-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "practice5-deploy-netlify"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
